name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.10.0
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: init
          BRANCH: gh-pages
          FOLDER: dist/main-app
          BUILD_SCRIPT: npm install && npm run build -- --prod