name: CI

on:
  push:
    branches:
      - init

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.10.0
      - run: npm install
        working-directory: main-app
      - run: npm run build --prod
        working-directory: main-app
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/main-app